/**
 * FeatureExtractor.ts
 *
 * Ekstrahuje cechy (features) z rekordów telemetry w celu późniejszej
 * analizy przez PatternDetector i PreferenceEngine.
 *
 * Moduł AI — NIE modyfikuje solvera. Tylko przygotowuje wektory cech.
 */

/** Pojedyńcza cecha wyekstrahowana z jednego rekordu */
export interface ExtractedFeature {
    name: string;
    value: string | number | boolean;
    weight: number;
    category: 'geometric' | 'user' | 'solver' | 'transition' | 'acceptance';
}

/** Wszystkie cechy dla jednego rekordu telemetry */
export interface FeatureVector {
    wellId: string;
    telemetryId: string;
    dn: string;
    features: ExtractedFeature[];
    extractedAt: string;
}

interface TransitionSnapshotInput {
    dn?: string | null;
    heightFromBottomMm?: number | null | undefined;
    transitionType?: string | null;
    producer?: string | null;
    angleDeg?: number | null;
    position?: string | null;
    transitionNo?: number | null;
}

interface ComponentInput {
    productId?: string;
    componentType?: string;
    height?: number;
    dn?: string | number;
}

interface TelemetryRecordLike {
    id: string;
    dn?: string | null;
    wellId?: string | null;
    warehouse?: string | null;
    wellType?: string | null;
    terminationType?: string | null;
    reductionType?: string | null;
    dennicaType?: string | null;
    dennicaHeight?: number | null;
    ringCount?: number | null;
    wasAutoGenerated?: boolean;
    wasAccepted?: boolean;
    wasRejected?: boolean;
    wasModified?: boolean;
    modificationCount?: number;
    confidenceScore?: number | null;
    rankingScore?: number | null;
}

/**
 * Ekstrahuje cechy z pojedynczego rekordu telemetry + listy przejść.
 *
 * @param record - rekord telemetry (ai_telemetry_logs)
 * @param transitions - lista ai_transition_snapshots dla tego rekordu
 * @param components - lista komponentów (allComponentIds lub snapshots)
 */
export class FeatureExtractor {
    extract(
        record: TelemetryRecordLike,
        transitions: TransitionSnapshotInput[] = [],
        components: ComponentInput[] = []
    ): FeatureVector {
        const features: ExtractedFeature[] = [];

        // ─── Cechy geometryczne ───
        features.push(
            { name: 'dn', value: record.dn || 'unknown', weight: 1.0, category: 'geometric' },
            {
                name: 'dennicaType',
                value: record.dennicaType || 'unknown',
                weight: 0.8,
                category: 'geometric'
            },
            {
                name: 'dennicaHeight',
                value: record.dennicaHeight ?? -1,
                weight: 0.9,
                category: 'geometric'
            },
            {
                name: 'ringCount',
                value: record.ringCount ?? 0,
                weight: 0.7,
                category: 'geometric'
            }
        );

        // ─── Cechy przejść szczelnych ───
        features.push({
            name: 'transitionCount',
            value: transitions.length,
            weight: 1.0,
            category: 'transition'
        });

        if (transitions.length > 0) {
            const avgHeight =
                transitions.reduce(function (acc, t) {
                    const h = typeof t.heightFromBottomMm === 'number' ? t.heightFromBottomMm : 0;
                    return acc + h;
                }, 0) / transitions.length;
            features.push({
                name: 'transitionAvgHeightMm',
                value: Math.round(avgHeight),
                weight: 0.9,
                category: 'transition'
            });

            const maxHeight = Math.max(
                ...transitions.map(function (t) {
                    return typeof t.heightFromBottomMm === 'number' ? t.heightFromBottomMm : 0;
                })
            );
            features.push({
                name: 'transitionMaxHeightMm',
                value: maxHeight,
                weight: 0.95,
                category: 'transition'
            });

            // Wzorzec rozmieszczenia przejść (np. "evenly_spaced" / "clustered")
            const heights = transitions
                .map(function (t) {
                    return typeof t.heightFromBottomMm === 'number' ? t.heightFromBottomMm : 0;
                })
                .sort(function (a, b) {
                    return a - b;
                });
            let spacing = 'unknown';
            if (heights.length >= 2) {
                const gaps: number[] = [];
                for (let i = 1; i < heights.length; i++) {
                    gaps.push(heights[i] - heights[i - 1]);
                }
                const avgGap =
                    gaps.reduce(function (a, b) {
                        return a + b;
                    }, 0) / gaps.length;
                const maxGap = Math.max.apply(null, gaps);
                spacing =
                    maxGap > avgGap * 2.5
                        ? 'clustered'
                        : maxGap < avgGap * 1.2
                          ? 'evenly_spaced'
                          : 'mixed';
            }
            features.push({
                name: 'transitionLayout',
                value: spacing,
                weight: 0.8,
                category: 'transition'
            });
        }

        // ─── Cechy solvera ───
        features.push(
            {
                name: 'wasAutoGenerated',
                value: record.wasAutoGenerated ?? false,
                weight: 0.9,
                category: 'solver'
            },
            {
                name: 'wasAccepted',
                value: record.wasAccepted ?? false,
                weight: 1.0,
                category: 'acceptance'
            },
            {
                name: 'wasRejected',
                value: record.wasRejected ?? false,
                weight: 1.0,
                category: 'acceptance'
            },
            {
                name: 'wasModified',
                value: record.wasModified ?? false,
                weight: 0.9,
                category: 'solver'
            },
            {
                name: 'modificationCount',
                value: record.modificationCount ?? 0,
                weight: 0.8,
                category: 'solver'
            }
        );

        // ─── Cechy biznesowe ───
        features.push(
            {
                name: 'warehouse',
                value: record.warehouse || 'unknown',
                weight: 0.5,
                category: 'user'
            },
            {
                name: 'wellType',
                value: record.wellType || 'standard',
                weight: 0.7,
                category: 'geometric'
            },
            {
                name: 'terminationType',
                value: record.terminationType || 'unknown',
                weight: 0.6,
                category: 'user'
            }
        );

        // ─── Komponenty ───
        if (components.length > 0) {
            features.push({
                name: 'componentCount',
                value: components.length,
                weight: 0.7,
                category: 'solver'
            });

            const reductionProducts = components.filter(function (c) {
                return (c.componentType || '').toLowerCase().includes('redukcj');
            }).length;
            features.push({
                name: 'reductionCount',
                value: reductionProducts,
                weight: 0.8,
                category: 'solver'
            });
        }

        return {
            wellId: record.wellId || 'unknown',
            telemetryId: record.id,
            dn: record.dn || 'unknown',
            features,
            extractedAt: new Date().toISOString()
        };
    }

    /**
     * Agregacja cech dla wszystkich rekordów (używa batch).
     */
    extractBatch(
        records: Array<{
            record: TelemetryRecordLike;
            transitions?: TransitionSnapshotInput[];
            components?: ComponentInput[];
        }>
    ): FeatureVector[] {
        const self = this;
        return records.map(function (r) {
            return self.extract(r.record, r.transitions, r.components);
        });
    }

    /**
     * Tworzy serializowalny hash cech (do porównań wzorców).
     */
    hash(featureVector: FeatureVector): string {
        const relevant = featureVector.features
            .filter(function (f) {
                return f.category !== 'user';
            })
            .map(function (f) {
                return f.name + '=' + f.value;
            })
            .sort()
            .join('|');
        return relevant;
    }
}
