/**
 * Telemetry AI - serwis zapisu i odczytu danych telemetry.
 *
 * Centralny punkt dla:
 * - zapisu konfiguracji studni z pełnym kontekstem,
 * - zapisu zdarzeń użytkownika (akceptacje, odrzucenia, zmiany),
 * - wersjonowania konfiguracji (pełna historia),
 * - zapisu przejść szczelnych (geometric features),
 * - rejestracji wersji solvera/reguł/AI.
 *
 * Moduł jest pasywny - solver JS pozostaje jedynym źródłem prawdy doboru.
 */

import crypto from 'crypto';
import { logger } from '../../utils/logger';
import prisma from '../../prismaClient';
import {
    type TelemetryConfigPayload,
    type TelemetryEventInput,
    type TelemetryRecordResponse,
    type VersionRegistrationInput
} from './telemetryTypes';

/* ===== SERWIS GŁÓWNY ===== */

class TelemetryService {
    /**
     * Zapisuje kompletną konfigurację z kontekstem wejściowym.
     * Tworzy równocześnie wersję historii oraz snapshot przejść szczelnych.
     */
    async recordConfig(
        payload: TelemetryConfigPayload,
        userId?: string
    ): Promise<TelemetryRecordResponse> {
        const now = new Date().toISOString();
        const telemetryId = crypto.randomUUID();
        const configHistoryId = crypto.randomUUID();

        try {
            // 1. Zapis głównego rekordu telemetry
            await prisma.ai_telemetry_logs.create({
                data: {
                    id: telemetryId,
                    userId: userId || null,
                    createdAt: now,
                    offerId: payload.offerId || null,
                    wellId: payload.wellId || null,
                    clientId: payload.clientId || null,
                    projectId: payload.projectId || null,
                    warehouse: payload.warehouse || null,
                    dn: payload.dn || null,
                    rzDna: payload.rzDna ?? null,
                    rzWlazu: payload.rzWlazu ?? null,
                    wellHeight: payload.wellHeight ?? null,
                    wellType: payload.wellType || null,
                    terminationType: payload.terminationType || null,
                    reductionType: payload.reductionType || null,
                    zwiencenieType: payload.zwiencenieType || null,
                    dennicaType: payload.dennicaType || null,
                    dennicaHeight: payload.dennicaHeight ?? null,
                    ringCount: payload.ringCount ?? null,
                    ringHeights: JSON.stringify(payload.ringHeights || []),
                    appliedReductions: JSON.stringify(payload.appliedReductions || []),
                    appliedKonus: JSON.stringify(payload.appliedKonus || []),
                    appliedHatches: JSON.stringify(payload.appliedHatches || []),
                    appliedSeals: JSON.stringify(payload.appliedSeals || []),
                    allComponentIds: JSON.stringify(payload.allComponentIds || []),
                    solverSource: payload.solverSource,
                    solverVersion: payload.solverVersion || null,
                    rulesVersion: payload.rulesVersion || null,
                    aiVersion: null,
                    computationMs: payload.computationMs ?? null,
                    iterationCount: payload.iterationCount ?? null,
                    checkedVariants: payload.checkedVariants ?? null,
                    rankingScore: payload.rankingScore ?? null,
                    selectionReason: payload.selectionReason || null,
                    wasAutoGenerated: payload.wasAutoGenerated ?? false,
                    wasAccepted: payload.wasAccepted ?? false,
                    wasRejected: payload.wasRejected ?? false,
                    wasModified: payload.wasModified ?? false,
                    modificationCount: payload.modificationCount ?? 0,
                    confidenceScore: payload.confidenceScore ?? null,
                    learningWeight: payload.learningWeight ?? null,
                    trainingEligible: true,
                    feedbackProcessed: false,
                    configVersion: payload.configVersion ?? 1,
                    parentConfigId: payload.parentConfigId || null,
                    reviewStatus: payload.reviewStatus || 'active',
                    featureSnapshot: JSON.stringify(payload.featureSnapshot || {}),
                    labelSnapshot: JSON.stringify(payload.labelSnapshot || {}),
                    predictionSnapshot: JSON.stringify(payload.predictionSnapshot || null),
                    rewardValue: null,
                    successRate: null,
                    usageCount: 1,
                    lastUsedAt: now,
                    manualOverrideFlag: !!payload.overrideReason
                }
            });

            // 2. Zapis wersji historii konfiguracji (jeśli wellId znany)
            let configHistoryCreated = false;
            if (payload.wellId) {
                await prisma.ai_config_history.create({
                    data: {
                        id: configHistoryId,
                        wellId: payload.wellId,
                        configVersion: payload.configVersion ?? 1,
                        parentId: payload.parentConfigId || null,
                        configJson: JSON.stringify({
                            originalConfig: payload.originalConfig || [],
                            finalConfig: payload.finalConfig || [],
                            components: payload.allComponentIds || []
                        }),
                        source: payload.solverSource,
                        triggeredBy: userId || null,
                        diffFromParent: JSON.stringify(
                            this._computeDiff(payload.originalConfig, payload.finalConfig)
                        ),
                        isCurrent: true,
                        rankingScore: payload.rankingScore ?? null,
                        selectionReason: payload.selectionReason || null,
                        createdAt: now
                    }
                });
                configHistoryCreated = true;
            }

            // 3. Snapshot przejść szczelnych
            let transitionsCreated = 0;
            if (payload.transitions && payload.transitions.length > 0) {
                for (let i = 0; i < payload.transitions.length; i++) {
                    const t = payload.transitions[i];
                    await prisma.ai_transition_snapshots.create({
                        data: {
                            id: crypto.randomUUID(),
                            wellId: payload.wellId || null,
                            configId: telemetryId,
                            transitionNo: t.transitionNo ?? i + 1,
                            dn: t.dn || null,
                            transitionType: t.transitionType || null,
                            producer: t.producer || null,
                            heightFromBottomMm: t.heightFromBottomMm ?? null,
                            angleDeg: t.angleDeg ?? null,
                            position: t.position || null,
                            collided: t.collided ?? false,
                            affectedDennicaHeight: t.affectedDennicaHeight ?? null,
                            affectedRingSelection: t.affectedRingSelection ?? false,
                            affectedReductionChoice: t.affectedReductionChoice ?? false,
                            affectedFinalConfig: t.affectedFinalConfig ?? false,
                            minimalDennicaForTransitionsMm: null,
                            solverModifiedForTransitions: false,
                            createdAt: now
                        }
                    });
                    transitionsCreated++;
                }
            }

            logger.info(
                'Telemetry',
                `Zapisano konfigurację ${telemetryId} ` +
                    `(well=${payload.wellId || 'brak'}, transitions=${transitionsCreated}, history=${configHistoryCreated})`
            );

            return {
                success: true,
                telemetryId,
                configHistoryId: configHistoryCreated ? configHistoryId : undefined,
                transitionsCreated
            };
        } catch (e) {
            const message = e instanceof Error ? e.message : String(e);
            logger.error('Telemetry', `Błąd zapisu konfiguracji: ${message}`);
            throw e;
        }
    }

    /**
     * Zapisuje pojedyncze zdarzenie telemetry (np. user_change, accept).
     */
    async recordEvent(
        event: TelemetryEventInput,
        userId?: string
    ): Promise<{ success: boolean; eventId: string }> {
        const eventId = crypto.randomUUID();
        const now = new Date().toISOString();

        try {
            await prisma.ai_telemetry_events.create({
                data: {
                    id: eventId,
                    telemetryId: event.telemetryId || null,
                    eventType: event.eventType,
                    userId: userId || null,
                    wellId: event.wellId || null,
                    componentId: event.componentId || null,
                    previousValue: event.previousValue || null,
                    newValue: event.newValue || null,
                    changeReason: event.changeReason || null,
                    msSinceConfig: event.msSinceConfig ?? null,
                    orderInSession: event.orderInSession ?? null,
                    sequenceNo: event.sequenceNo ?? 0,
                    createdAt: now
                }
            });
            return { success: true, eventId };
        } catch (e) {
            const message = e instanceof Error ? e.message : String(e);
            logger.error('Telemetry', `Błąd zapisu eventu: ${message}`);
            throw e;
        }
    }

    /**
     * Zapisuje wiele zdarzeń naraz (bulk insert przez wiele create).
     */
    async recordEventsBulk(
        events: TelemetryEventInput[],
        userId?: string
    ): Promise<{ success: boolean; created: number }> {
        let created = 0;
        for (const ev of events) {
            try {
                await this.recordEvent(ev, userId);
                created++;
            } catch (e) {
                logger.warn('Telemetry', `Pominięto event ${ev.eventType}: ${e}`);
            }
        }
        return { success: true, created };
    }

    /**
     * Rejestruje wersję solvera/reguł/AI.
     * Używane przy deployu lub gdy zmienia się logika solvera.
     */
    async registerVersion(
        input: VersionRegistrationInput
    ): Promise<{ success: boolean; id: string }> {
        const id = crypto.randomUUID();
        const now = new Date().toISOString();

        try {
            await prisma.ai_telemetry_versions.create({
                data: {
                    id,
                    componentType: input.componentType,
                    version: input.version,
                    description: input.description || null,
                    schemaVersion: input.schemaVersion || null,
                    isActive: input.isActive ?? true,
                    appliedFrom: 'Oferty_PV @ ' + now,
                    createdAt: now
                }
            });
            logger.info(
                'Telemetry',
                `Zarejestrowano wersję ${input.componentType}:${input.version}`
            );
            return { success: true, id };
        } catch (e) {
            const message = e instanceof Error ? e.message : String(e);
            logger.error('Telemetry', `Błąd rejestracji wersji: ${message}`);
            throw e;
        }
    }

    /**
     * Pobiera najnowsze rekordy telemetry (bez paginacji - do dashboardu admina).
     */
    async listRecent(limit: number = 100): Promise<Array<Record<string, unknown>>> {
        try {
            const logs = await prisma.ai_telemetry_logs.findMany({
                orderBy: { createdAt: 'desc' },
                take: limit
            });
            return logs.map((l) => this._safeDeserialize(l));
        } catch (e) {
            logger.error('Telemetry', `Błąd listy: ${e}`);
            return [];
        }
    }

    /**
     * Pobiera historię konfiguracji dla danej studni (well).
     */
    async getConfigHistory(wellId: string): Promise<Array<Record<string, unknown>>> {
        try {
            const history = await prisma.ai_config_history.findMany({
                where: { wellId },
                orderBy: { configVersion: 'desc' }
            });
            return history.map((h) => ({
                ...h,
                diffFromParent: this._safeJson(h.diffFromParent)
            }));
        } catch (e) {
            logger.error('Telemetry', `Błąd pobierania historii: ${e}`);
            return [];
        }
    }

    /**
     * Pobiera snapshot przejść szczelnych dla danej konfiguracji.
     */
    async getTransitions(configId: string): Promise<Array<Record<string, unknown>>> {
        try {
            const trans = await prisma.ai_transition_snapshots.findMany({
                where: { configId },
                orderBy: { transitionNo: 'asc' }
            });
            return trans;
        } catch (e) {
            logger.error('Telemetry', `Błąd pobierania przejść: ${e}`);
            return [];
        }
    }

    /**
     * Pobiera zdarzenia telemetry dla danej studni (well).
     */
    async getEvents(wellId: string): Promise<Array<Record<string, unknown>>> {
        try {
            const events = await prisma.ai_telemetry_events.findMany({
                where: { wellId },
                orderBy: { createdAt: 'asc' }
            });
            return events;
        } catch (e) {
            logger.error('Telemetry', `Błąd pobierania eventów: ${e}`);
            return [];
        }
    }

    /**
     * Pobiera aktywne wersje solvera/reguł/AI.
     */
    async getActiveVersions(): Promise<Array<Record<string, unknown>>> {
        try {
            return await prisma.ai_telemetry_versions.findMany({
                where: { isActive: true },
                orderBy: { createdAt: 'desc' }
            });
        } catch (e) {
            logger.error('Telemetry', `Błąd listy wersji: ${e}`);
            return [];
        }
    }

    /**
     * Oznacza konfigurację jako zaakceptowaną przez użytkownika
     * (pasuje do passive_learner.record_acceptance).
     */
    async recordAcceptance(telemetryId: string, accepted: boolean): Promise<void> {
        try {
            await prisma.ai_telemetry_logs.update({
                where: { id: telemetryId },
                data: {
                    wasAccepted: accepted,
                    wasRejected: !accepted,
                    lastAcceptedAt: accepted ? new Date().toISOString() : null,
                    lastRejectedAt: !accepted ? new Date().toISOString() : null,
                    usageCount: { increment: 1 },
                    lastUsedAt: new Date().toISOString()
                }
            });
        } catch (e) {
            logger.warn(
                'Telemetry',
                `Nie udało się zaktualizować acceptance dla ${telemetryId}: ${e}`
            );
        }
    }

    /**
     * Pomocnik: bezpieczna deserializacja JSON z obiektu Prisma.
     */
    private _safeDeserialize<T extends Record<string, unknown>>(obj: T): Record<string, unknown> {
        const result: Record<string, unknown> = { ...obj };
        const jsonFields = [
            'ringHeights',
            'appliedReductions',
            'appliedKonus',
            'appliedHatches',
            'appliedSeals',
            'allComponentIds',
            'featureSnapshot',
            'labelSnapshot',
            'predictionSnapshot',
            'original_auto_config',
            'final_user_config',
            'extraMeta'
        ];
        for (const field of jsonFields) {
            const val = result[field];
            if (typeof val === 'string') {
                try {
                    result[field] = JSON.parse(val);
                } catch {
                    /* zostaw surowy string */
                }
            }
        }
        return result;
    }

    private _safeJson(value: string | null | undefined): unknown {
        if (!value) return value;
        try {
            return JSON.parse(value);
        } catch {
            return value;
        }
    }

    private _computeDiff<T extends { productId?: string }>(
        original: T[] | undefined,
        final: T[] | undefined
    ): { added: string[]; removed: string[]; kept: string[] } {
        const orig = (original || []).map((c) => c.productId || '').filter(Boolean);
        const fin = (final || []).map((c) => c.productId || '').filter(Boolean);
        const origCounts = new Map<string, number>();
        const finCounts = new Map<string, number>();
        orig.forEach((id) => origCounts.set(id, (origCounts.get(id) || 0) + 1));
        fin.forEach((id) => finCounts.set(id, (finCounts.get(id) || 0) + 1));
        const added: string[] = [];
        const removed: string[] = [];
        const kept: string[] = [];
        const all = new Set([...origCounts.keys(), ...finCounts.keys()]);
        for (const id of all) {
            const o = origCounts.get(id) || 0;
            const f = finCounts.get(id) || 0;
            if (f > o) added.push(...Array(f - o).fill(id));
            else if (o > f) removed.push(...Array(o - f).fill(id));
            if (Math.min(o, f) > 0) kept.push(...Array(Math.min(o, f)).fill(id));
        }
        return { added, removed, kept };
    }
}

export const telemetryService = new TelemetryService();
