import crypto from 'crypto';
import { logger } from '../../utils/logger';
import prisma from '../../prismaClient';
import { type TelemetryConfigPayload, type TelemetryRecordResponse } from './telemetryTypes';
import { computeDiff } from './telemetryUtils';

export async function recordConfig(
    payload: TelemetryConfigPayload,
    userId?: string
): Promise<TelemetryRecordResponse> {
    const now = new Date().toISOString();
    const telemetryId = crypto.randomUUID();
    const configHistoryId = crypto.randomUUID();

    try {
        await prisma.$transaction(async (tx) => {
            await tx.ai_telemetry_logs.create({
                data: {
                    id: telemetryId,
                    userId: userId || null,
                    createdAt: now,
                    offerId: payload.offerId || null,
                    wellId: payload.wellId || null,
                    clientId: payload.clientId || null,
                    projectId: payload.projectId || null,
                    warehouse: payload.warehouse || null,
                    dn: payload.dn || null,
                    rzDna: payload.rzDna ?? null,
                    rzWlazu: payload.rzWlazu ?? null,
                    wellHeight: payload.wellHeight ?? null,
                    wellType: payload.wellType || null,
                    terminationType: payload.terminationType || null,
                    reductionType: payload.reductionType || null,
                    zwiencenieType: payload.zwiencenieType || null,
                    dennicaType: payload.dennicaType || null,
                    dennicaHeight: payload.dennicaHeight ?? null,
                    ringCount: payload.ringCount ?? null,
                    ringHeights: JSON.stringify(payload.ringHeights || []),
                    appliedReductions: JSON.stringify(payload.appliedReductions || []),
                    appliedKonus: JSON.stringify(payload.appliedKonus || []),
                    appliedHatches: JSON.stringify(payload.appliedHatches || []),
                    appliedSeals: JSON.stringify(payload.appliedSeals || []),
                    allComponentIds: JSON.stringify(payload.allComponentIds || []),
                    solverSource: payload.solverSource,
                    solverVersion: payload.solverVersion || null,
                    rulesVersion: payload.rulesVersion || null,
                    aiVersion: null,
                    computationMs: payload.computationMs ?? null,
                    iterationCount: payload.iterationCount ?? null,
                    checkedVariants: payload.checkedVariants ?? null,
                    rankingScore: payload.rankingScore ?? null,
                    selectionReason: payload.selectionReason || null,
                    wasAutoGenerated: payload.wasAutoGenerated ?? false,
                    wasAccepted: payload.wasAccepted ?? false,
                    wasRejected: payload.wasRejected ?? false,
                    wasModified: payload.wasModified ?? false,
                    modificationCount: payload.modificationCount ?? 0,
                    confidenceScore: payload.confidenceScore ?? null,
                    learningWeight: payload.learningWeight ?? null,
                    trainingEligible: true,
                    feedbackProcessed: false,
                    configVersion: payload.configVersion ?? 1,
                    parentConfigId: payload.parentConfigId || null,
                    reviewStatus: payload.reviewStatus || 'active',
                    featureSnapshot: JSON.stringify(payload.featureSnapshot || {}),
                    labelSnapshot: JSON.stringify(payload.labelSnapshot || {}),
                    predictionSnapshot: JSON.stringify(payload.predictionSnapshot || null),
                    rewardValue: null,
                    successRate: null,
                    usageCount: 1,
                    lastUsedAt: now,
                    manualOverrideFlag: !!payload.overrideReason
                }
            });

            if (payload.wellId) {
                await tx.ai_config_history.create({
                    data: {
                        id: configHistoryId,
                        wellId: payload.wellId,
                        configVersion: payload.configVersion ?? 1,
                        parentId: payload.parentConfigId || null,
                        configJson: JSON.stringify({
                            originalConfig: payload.originalConfig ?? [],
                            finalConfig: payload.finalConfig ?? [],
                            components: payload.allComponentIds || []
                        }),
                        source: payload.solverSource,
                        triggeredBy: userId || null,
                        diffFromParent: JSON.stringify(
                            computeDiff(
                                payload.originalConfig ?? undefined,
                                payload.finalConfig ?? undefined
                            )
                        ),
                        isCurrent: true,
                        rankingScore: payload.rankingScore ?? null,
                        selectionReason: payload.selectionReason || null,
                        createdAt: now
                    }
                });
            }

            if (payload.transitions && payload.transitions.length > 0) {
                const transitionData = payload.transitions.map((t, i) => ({
                    id: crypto.randomUUID(),
                    wellId: payload.wellId || null,
                    configId: telemetryId,
                    transitionNo: t.transitionNo ?? i + 1,
                    dn: t.dn || null,
                    transitionType: t.transitionType || null,
                    producer: t.producer || null,
                    heightFromBottomMm: t.heightFromBottomMm ?? null,
                    angleDeg: t.angleDeg ?? null,
                    position: t.position || null,
                    collided: t.collided ?? false,
                    affectedDennicaHeight: t.affectedDennicaHeight ?? null,
                    affectedRingSelection: t.affectedRingSelection ?? false,
                    affectedReductionChoice: t.affectedReductionChoice ?? false,
                    affectedFinalConfig: t.affectedFinalConfig ?? false,
                    minimalDennicaForTransitionsMm: null,
                    solverModifiedForTransitions: false,
                    createdAt: now
                }));
                await tx.ai_transition_snapshots.createMany({ data: transitionData });
            }
        });

        const configHistoryCreated = !!payload.wellId;
        const transitionsCreated = payload.transitions?.length ?? 0;

        logger.info(
            'Telemetry',
            `Zapisano konfigurację ${telemetryId} ` +
                `(well=${payload.wellId || 'brak'}, transitions=${transitionsCreated}, history=${configHistoryCreated})`
        );

        return {
            success: true,
            telemetryId,
            configHistoryId: configHistoryCreated ? configHistoryId : undefined,
            transitionsCreated
        };
    } catch (e) {
        const message = e instanceof Error ? e.message : String(e);
        logger.error('Telemetry', `Błąd zapisu konfiguracji: ${message}`);
        throw e;
    }
}
