/**
 * Telemetry AI — typy i interfejsy.
 *
 * Moduł telemetry jest pasywny — solver JS pozostaje jedynym źródłem prawdy
 * dla doboru elementów studni. AI w przyszłości jedynie analizuje zgromadzone
 * dane i rekomenduje wybór spośród technicznie poprawnych konfiguracji.
 */

/** Źródło konfiguracji */
export type SolverSource = 'AUTO_JS' | 'MANUAL' | 'AI_SUGGEST';

/** Status wersji konfiguracji */
export type ReviewStatus = 'active' | 'archived' | 'shadowed';

/** Event typy */
export type TelemetryEventType =
    | 'auto_run'
    | 'user_change'
    | 'accept'
    | 'reject'
    | 'save_offer'
    | 'create_order'
    | 'telemetry_reason'
    | 'rule_violation'
    | 'fallback_triggered'
    | 'ai_rank_decision';

/** Komponent studni (pojedynczy element w config) */
export interface WellComponentSnapshot {
    productId: string;
    productName?: string | null;
    componentType?: string | null;
    dn?: string | number | null;
    height?: number | null;
    width?: number | null;
    position?: number | null;
    isReduction?: boolean | null;
    isKonus?: boolean | null;
    isHatch?: boolean | null;
    isSeal?: boolean | null;
}

/** Przejście szczelne */
export interface TransitionSnapshot {
    transitionNo: number;
    dn?: string;
    transitionType?: string | null;
    producer?: string | null;
    heightFromBottomMm?: number | null;
    angleDeg?: number | null;
    position?: string | null;
    collided?: boolean | null;
    affectedDennicaHeight?: number | null;
    affectedRingSelection?: boolean | null;
    affectedReductionChoice?: boolean | null;
    affectedFinalConfig?: boolean | null;
}

/** Pełny payload telemetry — struktura wejściowa do API */
export interface TelemetryConfigPayload {
    // Kontekst studni (opcjonalny)
    offerId?: string;
    wellId?: string;
    clientId?: string;
    projectId?: string;
    warehouse?: string;

    // Parametry wejściowe studni
    dn?: string;
    rzDna?: number;
    rzWlazu?: number;
    wellHeight?: number;
    wellType?: string;
    terminationType?: string;
    reductionType?: string;
    zwiencenieType?: string;
    dennicaType?: string;
    dennicaHeight?: number;
    ringCount?: number;
    ringHeights?: number[];

    // Komponenty (snapshot wszystkich wybranych)
    appliedReductions?: WellComponentSnapshot[];
    appliedKonus?: WellComponentSnapshot[];
    appliedHatches?: WellComponentSnapshot[];
    appliedSeals?: WellComponentSnapshot[];
    allComponentIds?: string[];

    // Solver metadata
    solverSource: SolverSource;
    solverVersion?: string | null;
    rulesVersion?: string | null;
    computationMs?: number | null;
    iterationCount?: number | null;
    checkedVariants?: number | null;
    rankingScore?: number | null;
    selectionReason?: string | null;

    // Boolean flagi
    wasAutoGenerated?: boolean;
    wasAccepted?: boolean;
    wasRejected?: boolean;
    wasModified?: boolean;
    modificationCount?: number | null;
    confidenceScore?: number | null;
    learningWeight?: number | null;

    // Wersjonowanie
    configVersion?: number | null;
    parentConfigId?: string | null;
    reviewStatus?: ReviewStatus | null;

    // Features/labels (pod przyszłe AI)
    featureSnapshot?: Record<string, unknown> | null;
    labelSnapshot?: Record<string, unknown> | null;
    predictionSnapshot?: Record<string, unknown> | null;

    // Przejścia szczelne — wydzielone od zwykłych komponentów
    transitions?: TransitionSnapshot[] | null;

    // Original vs final config (korekty użytkownika)
    originalConfig?: WellComponentSnapshot[] | null;
    finalConfig?: WellComponentSnapshot[] | null;
    overrideReason?: string | null;
}

/** Event telemetry (pojedyncza akcja) */
export interface TelemetryEventInput {
    telemetryId?: string;
    eventType: TelemetryEventType;
    wellId?: string;
    componentId?: string;
    previousValue?: string;
    newValue?: string;
    changeReason?: string;
    msSinceConfig?: number;
    orderInSession?: number;
    sequenceNo?: number;
}

/** Model pełnej historii wersji konfiguracji */
export interface ConfigHistoryInput {
    wellId: string;
    configVersion: number;
    parentId?: string;
    configJson: Record<string, unknown>;
    source: SolverSource;
    triggeredBy?: string;
    diffFromParent?: WellComponentSnapshot[];
    rankingScore?: number;
    selectionReason?: string;
}

/** Wersje solvera/reguł/AI */
export interface VersionRegistrationInput {
    componentType: 'solver' | 'rules' | 'ai' | 'embedding';
    version: string;
    description?: string;
    schemaVersion?: string;
    isActive?: boolean;
}

/** Odpowiedź API z zapisu telemetry */
export interface TelemetryRecordResponse {
    success: boolean;
    telemetryId: string;
    configHistoryId?: string;
    eventsCreated?: number;
    transitionsCreated?: number;
}

/** Odpowiedź API z list telemetry */
export interface TelemetryListResponse<T = unknown> {
    items: T[];
    total: number;
    page?: number;
    pageSize?: number;
}

/** Wagi preferencji (placeholder dla przyszłego AI) */
export interface PreferenceWeights {
    substitution: Map<string, { replaceWith: string; weight: number; confidence: number }>;
    addition: Map<string, { weight: number; confidence: number }>;
    removal: Map<string, { weight: number; confidence: number }>;
}

/** Config wejściowy dla pasywnego hooka w solverze JS */
export interface PassiveHookData {
    configId?: string;
    wellId?: string;
    iterations?: number;
    variants?: number;
    transitionsCount?: number;
    collisionsCount?: number;
    fallbackUsed?: boolean;
    rankingScore?: number;
    selectionReason?: string;
    msStart?: number;
}
