-- =============================================================================
-- Migracja: telemetry_ai_prep
-- Dodanie pól telemetry, eventów, wersji konfiguracji, wersji solvera i przejść
-- szczelnych do systemu AI telemetry. Wszystko jest pasywne - solver JS
-- pozostaje deterministycznym źródłem prawdy.
-- =============================================================================

-- nowe tabele
CREATE TABLE IF NOT EXISTS "ai_telemetry_events" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "telemetryId" TEXT,
    "eventType" TEXT NOT NULL,
    "userId" TEXT,
    "wellId" TEXT,
    "componentId" TEXT,
    "previousValue" TEXT,
    "newValue" TEXT,
    "changeReason" TEXT,
    "msSinceConfig" INTEGER,
    "orderInSession" INTEGER,
    "sequenceNo" INTEGER DEFAULT 0,
    "createdAt" TEXT
);

CREATE TABLE IF NOT EXISTS "ai_config_history" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "wellId" TEXT,
    "configVersion" INTEGER NOT NULL,
    "parentId" TEXT,
    "configJson" TEXT,
    "source" TEXT,
    "triggeredBy" TEXT,
    "diffFromParent" TEXT,
    "isCurrent" BOOLEAN NOT NULL DEFAULT true,
    "rankingScore" REAL,
    "selectionReason" TEXT,
    "createdAt" TEXT
);

CREATE TABLE IF NOT EXISTS "ai_telemetry_versions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "componentType" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "description" TEXT,
    "schemaVersion" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "appliedFrom" TEXT,
    "createdAt" TEXT
);

CREATE TABLE IF NOT EXISTS "ai_transition_snapshots" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "wellId" TEXT,
    "configId" TEXT,
    "transitionNo" INTEGER,
    "dn" TEXT,
    "transitionType" TEXT,
    "producer" TEXT,
    "heightFromBottomMm" REAL,
    "angleDeg" REAL,
    "position" TEXT,
    "collided" BOOLEAN NOT NULL DEFAULT false,
    "affectedDennicaHeight" REAL,
    "affectedRingSelection" BOOLEAN NOT NULL DEFAULT false,
    "affectedReductionChoice" BOOLEAN NOT NULL DEFAULT false,
    "affectedFinalConfig" BOOLEAN NOT NULL DEFAULT false,
    "minimalDennicaForTransitionsMm" REAL,
    "solverModifiedForTransitions" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TEXT
);

-- redefine ai_telemetry_logs z nowymi polami
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ai_telemetry_logs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "original_auto_config" TEXT,
    "final_user_config" TEXT,
    "override_reason" TEXT,
    "createdAt" TEXT,
    "offerId" TEXT,
    "wellId" TEXT,
    "clientId" TEXT,
    "projectId" TEXT,
    "warehouse" TEXT,
    "dn" TEXT,
    "rzDna" REAL,
    "rzWlazu" REAL,
    "wellHeight" REAL,
    "wellType" TEXT,
    "terminationType" TEXT,
    "reductionType" TEXT,
    "zwiencenieType" TEXT,
    "dennicaType" TEXT,
    "dennicaHeight" REAL,
    "ringCount" INTEGER,
    "ringHeights" TEXT,
    "appliedReductions" TEXT,
    "appliedKonus" TEXT,
    "appliedHatches" TEXT,
    "appliedSeals" TEXT,
    "allComponentIds" TEXT,
    "solverSource" TEXT,
    "solverVersion" TEXT,
    "rulesVersion" TEXT,
    "aiVersion" TEXT,
    "computationMs" INTEGER,
    "iterationCount" INTEGER,
    "checkedVariants" INTEGER,
    "rankingScore" REAL,
    "selectionReason" TEXT,
    "wasAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "wasAccepted" BOOLEAN NOT NULL DEFAULT false,
    "wasRejected" BOOLEAN NOT NULL DEFAULT false,
    "wasModified" BOOLEAN NOT NULL DEFAULT false,
    "modificationCount" INTEGER DEFAULT 0,
    "confidenceScore" REAL,
    "learningWeight" REAL,
    "trainingEligible" BOOLEAN NOT NULL DEFAULT true,
    "feedbackProcessed" BOOLEAN NOT NULL DEFAULT false,
    "configVersion" INTEGER DEFAULT 1,
    "parentConfigId" TEXT,
    "reviewStatus" TEXT DEFAULT 'active',
    "featureSnapshot" TEXT,
    "labelSnapshot" TEXT,
    "predictionSnapshot" TEXT,
    "rewardValue" REAL,
    "successRate" REAL,
    "usageCount" INTEGER DEFAULT 1,
    "lastUsedAt" TEXT,
    "lastAcceptedAt" TEXT,
    "lastRejectedAt" TEXT,
    "manualOverrideFlag" BOOLEAN NOT NULL DEFAULT false,
    "extraMeta" TEXT
);
INSERT INTO "new_ai_telemetry_logs" (
    "id", "userId", "original_auto_config", "final_user_config",
    "override_reason", "createdAt"
) SELECT
    "id", "userId", "original_auto_config", "final_user_config",
    "override_reason", "createdAt"
FROM "ai_telemetry_logs";
DROP TABLE "ai_telemetry_logs";
ALTER TABLE "new_ai_telemetry_logs" RENAME TO "ai_telemetry_logs";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- indeksy
CREATE INDEX IF NOT EXISTS "idx_events_telemetry" ON "ai_telemetry_events"("telemetryId");
CREATE INDEX IF NOT EXISTS "idx_events_well" ON "ai_telemetry_events"("wellId");
CREATE INDEX IF NOT EXISTS "idx_events_type" ON "ai_telemetry_events"("eventType");
CREATE INDEX IF NOT EXISTS "idx_events_user" ON "ai_telemetry_events"("userId");
CREATE INDEX IF NOT EXISTS "idx_events_createdat" ON "ai_telemetry_events"("createdAt");

CREATE INDEX IF NOT EXISTS "idx_history_well" ON "ai_config_history"("wellId");
CREATE INDEX IF NOT EXISTS "idx_history_well_current" ON "ai_config_history"("wellId", "isCurrent");

CREATE INDEX IF NOT EXISTS "idx_versions_active" ON "ai_telemetry_versions"("componentType", "isActive");

CREATE INDEX IF NOT EXISTS "idx_transitions_well" ON "ai_transition_snapshots"("wellId");
CREATE INDEX IF NOT EXISTS "idx_transitions_config" ON "ai_transition_snapshots"("configId");
