/**
 * Testy modułu telemetry AI.
 *
 * Weryfikują:
 * - walidację schematów Zod (payload/konfiguracja/event/wersja/acceptance),
 * - deserializację JSON w telemetryTypes,
 * - poprawność telemetrii (bez wpływu na solver).
 */

import { describe, expect, it } from '@jest/globals';
import {
    telemetryAcceptanceSchema,
    telemetryConfigSchema,
    telemetryEventSchema,
    telemetryVersionSchema
} from '../src/validators/telemetrySchemas';

/* ===== Walidacja telemetryConfigSchema ===== */

describe('telemetryConfigSchema', () => {
    it('akceptuje minimalny wymagany payload', () => {
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS'
        });
        expect(r.success).toBe(true);
    });

    it('akceptuje pełny payload z przejściami', () => {
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS',
            dn: '1200',
            rzDna: 105.5,
            rzWlazu: 109.5,
            wellHeight: 4000,
            warehouse: 'KLB',
            appliedReductions: [{ productId: 'P1', componentType: 'redukcja' }],
            appliedKonus: [{ productId: 'P2', componentType: 'konus' }],
            appliedHatches: [{ productId: 'P3', componentType: 'właz' }],
            allComponentIds: ['P1', 'P2', 'P3'],
            transitions: [
                {
                    transitionNo: 1,
                    dn: '160',
                    transitionType: 'rura_przejściowa',
                    heightFromBottomMm: 250
                }
            ],
            solverVersion: '2.0.0',
            rulesVersion: '2026-06-30.1',
            computationMs: 150,
            iterationCount: 1,
            wasAutoGenerated: true,
            featureSnapshot: { dn: '1200' },
            labelSnapshot: { score: 8.5 }
        });
        expect(r.success).toBe(true);
        if (r.success) {
            expect(r.data.dn).toBe('1200');
            expect(r.data.transitions?.length).toBe(1);
            expect(r.data.rzDna).toBe(105.5);
        }
    });

    it('odrzuca payload bez solverSource', () => {
        const r = telemetryConfigSchema.safeParse({ dn: '1000' });
        expect(r.success).toBe(false);
    });

    it('odrzuca zły enum solverSource', () => {
        const r = telemetryConfigSchema.safeParse({ solverSource: 'NIEISTNIEJĄCY' });
        expect(r.success).toBe(false);
    });

    it('wymaga popRawnego typu solvera (tylko 4 wartosci)', () => {
        ['AUTO_JS', 'AUTO_PYTHON', 'MANUAL', 'AI_SUGGEST'].forEach(function (s) {
            expect(telemetryConfigSchema.safeParse({ solverSource: s }).success).toBe(true);
        });
        expect(telemetryConfigSchema.safeParse({ solverSource: 'HACK' }).success).toBe(false);
    });

    it('akceptuje predictionSnapshot jako null', () => {
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS',
            predictionSnapshot: null
        });
        expect(r.success).toBe(true);
    });

    it('rzDna jako string jest konwertowane na number', () => {
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS',
            rzDna: '105.5'
        });
        expect(r.success).toBe(true);
        if (r.success) {
            expect(r.data.rzDna).toBe(105.5);
            expect(typeof r.data.rzDna).toBe('number');
        }
    });

    it('rzDna jako number też przechodzi', () => {
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS',
            rzDna: 200
        });
        expect(r.success).toBe(true);
        if (r.success) expect(r.data.rzDna).toBe(200);
    });
});

/* ===== Walidacja telemetryEventSchema ===== */

describe('telemetryEventSchema', () => {
    it('minimalny event z eventType', () => {
        const r = telemetryEventSchema.safeParse({ eventType: 'auto_run' });
        expect(r.success).toBe(true);
    });

    it('akceptuje pełny event', () => {
        const r = telemetryEventSchema.safeParse({
            eventType: 'user_change',
            wellId: 'W1',
            componentId: 'C1',
            previousValue: 'P_X',
            newValue: 'P_Y',
            changeReason: 'dłuższa dennica',
            msSinceConfig: 5000,
            sequenceNo: 3
        });
        expect(r.success).toBe(true);
        if (r.success) {
            expect(r.data.eventType).toBe('user_change');
            expect(r.data.previousValue).toBe('P_X');
        }
    });

    it('odrzuca zły eventType', () => {
        const r = telemetryEventSchema.safeParse({ eventType: 'fake_event' });
        expect(r.success).toBe(false);
    });

    it('akceptuje wszystkie 9 event types', () => {
        const events = [
            'auto_run',
            'user_change',
            'accept',
            'reject',
            'save_offer',
            'create_order',
            'telemetry_reason',
            'rule_violation',
            'fallback_triggered'
        ];
        events.forEach(function (e) {
            expect(telemetryEventSchema.safeParse({ eventType: e }).success).toBe(true);
        });
    });
});

/* ===== Walidacja telemetryVersionSchema ===== */

describe('telemetryVersionSchema', () => {
    it('wymaga componentType i version', () => {
        expect(
            telemetryVersionSchema.safeParse({ componentType: 'solver', version: '2.0.0' }).success
        ).toBe(true);
        expect(telemetryVersionSchema.safeParse({ componentType: 'solver' }).success).toBe(false);
        expect(telemetryVersionSchema.safeParse({ version: '2.0.0' }).success).toBe(false);
    });

    it('akceptuje componentType z listy', () => {
        ['solver', 'rules', 'ai', 'embedding'].forEach(function (t) {
            expect(
                telemetryVersionSchema.safeParse({
                    componentType: t,
                    version: '1.0.0'
                }).success
            ).toBe(true);
        });
        expect(
            telemetryVersionSchema.safeParse({
                componentType: 'unknown',
                version: '1.0.0'
            }).success
        ).toBe(false);
    });
});

/* ===== Walidacja telemetryAcceptanceSchema ===== */

describe('telemetryAcceptanceSchema', () => {
    it('wymaga telemetryId i accepted', () => {
        expect(
            telemetryAcceptanceSchema.safeParse({
                telemetryId: 'a1',
                accepted: true
            }).success
        ).toBe(true);

        expect(telemetryAcceptanceSchema.safeParse({ accepted: true }).success).toBe(false);
        expect(telemetryAcceptanceSchema.safeParse({ telemetryId: 'a1' }).success).toBe(false);
    });
});

/* ===== Testy "pasywności" — telemetria nie blokuje solvera ===== */

/**
 * Test weryfikujący że telemetryService NIE jest zależny
 * od wyniku solvera. Jeśli endpoint zawiedzie, nic się nie psuje.
 */
describe('telemetry - pasywność', () => {
    it('schema akceptuje payload bez pól solvera (null/undefined)', () => {
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS',
            computationMs: undefined,
            rankingScore: undefined,
            transitions: undefined
        });
        expect(r.success).toBe(true);
    });

    it('schema akceptuje bardzo duży payload (bez limitu znaków)', () => {
        const hugeComponents = Array(500)
            .fill(0)
            .map(function (_, i) {
                return {
                    productId: 'P' + i,
                    componentType: 'krag',
                    dn: '1000'
                };
            });
        const r = telemetryConfigSchema.safeParse({
            solverSource: 'AUTO_JS',
            allComponentIds: hugeComponents.map(function (c) {
                return c.productId;
            })
        });
        expect(r.success).toBe(true);
    });
});
