/**
 * Schematy walidacji Zod dla telemetry AI.
 *
 * Używane przez /api/telemetry/ai* endpointy do walidacji
 * payloadów z frontend (JS solver).
 */

import { z } from 'zod';

// =============================================================================
// Komponent studni (snapshot)
// =============================================================================

const wellComponentSchema = z.object({
    productId: z.string(),
    productName: z.string().optional(),
    componentType: z.string(),
    dn: z.union([z.string(), z.number()]).optional(),
    height: z.number().optional(),
    width: z.number().optional(),
    position: z.number().optional(),
    isReduction: z.boolean().optional(),
    isKonus: z.boolean().optional(),
    isHatch: z.boolean().optional(),
    isSeal: z.boolean().optional()
});

// =============================================================================
// Przejście szczelne
// =============================================================================

const transitionSchema = z.object({
    transitionNo: z.number().int().positive(),
    dn: z.string(),
    transitionType: z.string().optional(),
    producer: z.string().optional(),
    heightFromBottomMm: z.number().optional(),
    angleDeg: z.number().optional(),
    position: z.string().optional(),
    collided: z.boolean().optional(),
    affectedDennicaHeight: z.number().optional(),
    affectedRingSelection: z.boolean().optional(),
    affectedReductionChoice: z.boolean().optional(),
    affectedFinalConfig: z.boolean().optional()
});

// =============================================================================
// Pełny payload konfiguracji telemetry
// =============================================================================

export const telemetryConfigSchema = z.object({
    // Kontekst studni
    offerId: z.string().optional(),
    wellId: z.string().optional(),
    clientId: z.string().optional(),
    projectId: z.string().optional(),
    warehouse: z.string().optional(),

    // Parametry wejściowe studni
    dn: z.string().optional(),
    rzDna: z
        .union([z.number(), z.string()])
        .optional()
        .transform((v) =>
            v === undefined ? undefined : typeof v === 'string' ? parseFloat(v) : v
        ),
    rzWlazu: z
        .union([z.number(), z.string()])
        .optional()
        .transform((v) =>
            v === undefined ? undefined : typeof v === 'string' ? parseFloat(v) : v
        ),
    wellHeight: z
        .union([z.number(), z.string()])
        .optional()
        .transform((v) =>
            v === undefined ? undefined : typeof v === 'string' ? parseFloat(v) : v
        ),
    wellType: z.string().optional(),
    terminationType: z.string().optional(),
    reductionType: z.string().optional(),
    zwiencenieType: z.string().optional(),
    dennicaType: z.string().optional(),
    dennicaHeight: z
        .union([z.number(), z.string()])
        .optional()
        .transform((v) =>
            v === undefined ? undefined : typeof v === 'string' ? parseFloat(v) : v
        ),
    ringCount: z.number().int().optional(),
    ringHeights: z.array(z.number()).optional(),

    // Komponenty
    appliedReductions: z.array(wellComponentSchema).optional(),
    appliedKonus: z.array(wellComponentSchema).optional(),
    appliedHatches: z.array(wellComponentSchema).optional(),
    appliedSeals: z.array(wellComponentSchema).optional(),
    allComponentIds: z.array(z.string()).optional(),

    // Solver metadata
    solverSource: z.enum(['AUTO_JS', 'MANUAL', 'AI_SUGGEST']),
    solverVersion: z.string().optional(),
    rulesVersion: z.string().optional(),
    computationMs: z.number().int().optional(),
    iterationCount: z.number().int().optional(),
    checkedVariants: z.number().int().optional(),
    rankingScore: z.number().optional(),
    selectionReason: z.string().optional(),

    // Boolean flagi
    wasAutoGenerated: z.boolean().optional(),
    wasAccepted: z.boolean().optional(),
    wasRejected: z.boolean().optional(),
    wasModified: z.boolean().optional(),
    modificationCount: z.number().int().optional(),
    confidenceScore: z.number().optional(),
    learningWeight: z.number().optional(),

    // Wersjonowanie
    configVersion: z.number().int().optional(),
    parentConfigId: z.string().optional(),
    reviewStatus: z.enum(['active', 'archived', 'shadowed']).optional(),

    // Features/labels/predictions
    featureSnapshot: z.record(z.string(), z.unknown()).optional(),
    labelSnapshot: z.record(z.string(), z.unknown()).optional(),
    predictionSnapshot: z.record(z.string(), z.unknown()).nullable().optional(),

    // Przejścia szczelne
    transitions: z.array(transitionSchema).optional(),

    // Original vs final (korekty)
    originalConfig: z.array(wellComponentSchema).optional(),
    finalConfig: z.array(wellComponentSchema).optional(),
    overrideReason: z.string().optional()
});

export type TelemetryConfigInput = Omit<
    z.infer<typeof telemetryConfigSchema>,
    'predictionSnapshot' | 'rzDna' | 'rzWlazu' | 'wellHeight' | 'dennicaHeight'
> & {
    predictionSnapshot?: Record<string, unknown> | null;
    rzDna?: number;
    rzWlazu?: number;
    wellHeight?: number;
    dennicaHeight?: number;
};

// =============================================================================
// Event telemetry
// =============================================================================

export const telemetryEventSchema = z.object({
    telemetryId: z.string().optional(),
    eventType: z.enum([
        'auto_run',
        'user_change',
        'accept',
        'reject',
        'save_offer',
        'create_order',
        'telemetry_reason',
        'rule_violation',
        'fallback_triggered'
    ]),
    wellId: z.string().optional(),
    componentId: z.string().optional(),
    previousValue: z.string().optional(),
    newValue: z.string().optional(),
    changeReason: z.string().optional(),
    msSinceConfig: z.number().int().optional(),
    orderInSession: z.number().int().optional(),
    sequenceNo: z.number().int().optional()
});

export type TelemetryEventInputType = z.infer<typeof telemetryEventSchema>;

// =============================================================================
// Bulk events
// =============================================================================

export const telemetryEventsBulkSchema = z.object({
    events: z.array(telemetryEventSchema).min(1).max(500)
});

export type TelemetryEventsBulkInput = z.infer<typeof telemetryEventsBulkSchema>;

// =============================================================================
// Wersja (solver/reguły/AI)
// =============================================================================

export const telemetryVersionSchema = z.object({
    componentType: z.enum(['solver', 'rules', 'ai', 'embedding']),
    version: z.string().min(1),
    description: z.string().optional(),
    schemaVersion: z.string().optional(),
    isActive: z.boolean().optional()
});

export type TelemetryVersionInput = z.infer<typeof telemetryVersionSchema>;

// =============================================================================
// Acceptance update (tryb pasywnego ML)
// =============================================================================

export const telemetryAcceptanceSchema = z.object({
    telemetryId: z.string(),
    accepted: z.boolean()
});

export type TelemetryAcceptanceInput = z.infer<typeof telemetryAcceptanceSchema>;

// =============================================================================
// Acceptance Full — rozszerzony acceptance z pełnym kontekstem oferty
// =============================================================================

export const telemetryAcceptanceFullSchema = z.object({
    telemetryId: z.string(),
    accepted: z.boolean(),
    offerId: z.string().optional(),
    wellId: z.string().optional(),
    configSnapshot: z.record(z.string(), z.unknown()).optional(),
    transitions: z.array(z.record(z.string(), z.unknown())).optional(),
    warehouse: z.string().optional(),
    originalConfig: z.array(z.record(z.string(), z.unknown())).optional(),
    finalConfig: z.array(z.record(z.string(), z.unknown())).optional()
});

export type TelemetryAcceptanceFullInput = z.infer<typeof telemetryAcceptanceFullSchema>;
