-- CreateTable
CREATE TABLE "ai_telemetry_logs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "original_auto_config" TEXT,
    "final_user_config" TEXT,
    "override_reason" TEXT,
    "createdAt" TEXT,
    "offerId" TEXT,
    "wellId" TEXT,
    "clientId" TEXT,
    "projectId" TEXT,
    "warehouse" TEXT,
    "dn" TEXT,
    "rzDna" REAL,
    "rzWlazu" REAL,
    "wellHeight" REAL,
    "wellType" TEXT,
    "terminationType" TEXT,
    "reductionType" TEXT,
    "zwiencenieType" TEXT,
    "dennicaType" TEXT,
    "dennicaHeight" REAL,
    "kineta" TEXT,
    "ringCount" INTEGER,
    "ringHeights" TEXT,
    "appliedReductions" TEXT,
    "appliedKonus" TEXT,
    "appliedHatches" TEXT,
    "appliedSeals" TEXT,
    "allComponentIds" TEXT,
    "solverSource" TEXT,
    "solverVersion" TEXT,
    "rulesVersion" TEXT,
    "aiVersion" TEXT,
    "computationMs" INTEGER,
    "iterationCount" INTEGER,
    "checkedVariants" INTEGER,
    "rankingScore" REAL,
    "selectionReason" TEXT,
    "wasAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "wasAccepted" BOOLEAN NOT NULL DEFAULT false,
    "wasRejected" BOOLEAN NOT NULL DEFAULT false,
    "wasModified" BOOLEAN NOT NULL DEFAULT false,
    "modificationCount" INTEGER DEFAULT 0,
    "confidenceScore" REAL,
    "learningWeight" REAL,
    "trainingEligible" BOOLEAN NOT NULL DEFAULT true,
    "feedbackProcessed" BOOLEAN NOT NULL DEFAULT false,
    "configVersion" INTEGER DEFAULT 1,
    "parentConfigId" TEXT,
    "reviewStatus" TEXT DEFAULT 'active',
    "featureSnapshot" TEXT,
    "labelSnapshot" TEXT,
    "predictionSnapshot" TEXT,
    "rewardValue" REAL,
    "successRate" REAL,
    "usageCount" INTEGER DEFAULT 1,
    "lastUsedAt" TEXT,
    "lastAcceptedAt" TEXT,
    "lastRejectedAt" TEXT,
    "manualOverrideFlag" BOOLEAN NOT NULL DEFAULT false,
    "extraMeta" TEXT
);

-- CreateTable
CREATE TABLE "ai_telemetry_events" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "telemetryId" TEXT,
    "eventType" TEXT NOT NULL,
    "userId" TEXT,
    "wellId" TEXT,
    "componentId" TEXT,
    "previousValue" TEXT,
    "newValue" TEXT,
    "changeReason" TEXT,
    "msSinceConfig" INTEGER,
    "orderInSession" INTEGER,
    "sequenceNo" INTEGER DEFAULT 0,
    "createdAt" TEXT
);

-- CreateTable
CREATE TABLE "ai_config_history" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "wellId" TEXT,
    "configVersion" INTEGER NOT NULL,
    "parentId" TEXT,
    "configJson" TEXT,
    "source" TEXT,
    "triggeredBy" TEXT,
    "diffFromParent" TEXT,
    "isCurrent" BOOLEAN NOT NULL DEFAULT true,
    "rankingScore" REAL,
    "selectionReason" TEXT,
    "createdAt" TEXT
);

-- CreateTable
CREATE TABLE "ai_telemetry_versions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "componentType" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "description" TEXT,
    "schemaVersion" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "appliedFrom" TEXT,
    "createdAt" TEXT
);

-- CreateTable
CREATE TABLE "ai_knowledge_base" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "patternType" TEXT NOT NULL,
    "patternKey" TEXT NOT NULL,
    "dn" TEXT,
    "context" TEXT,
    "description" TEXT,
    "recommendation" TEXT,
    "hitCount" INTEGER NOT NULL DEFAULT 0,
    "confidence" REAL NOT NULL DEFAULT 0.0,
    "successCount" INTEGER NOT NULL DEFAULT 0,
    "rejectionCount" INTEGER NOT NULL DEFAULT 0,
    "firstDetectedAt" TEXT,
    "lastHitAt" TEXT,
    "lastUpdatedAt" TEXT,
    "changeHistory" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "schemaVersion" TEXT,
    "generatedBy" TEXT
);

-- CreateTable
CREATE TABLE "ai_recommendations" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "patternType" TEXT NOT NULL,
    "patternKey" TEXT NOT NULL,
    "dn" TEXT,
    "wellId" TEXT,
    "score" REAL NOT NULL DEFAULT 0.0,
    "confidence" REAL NOT NULL DEFAULT 0.0,
    "payload" TEXT,
    "wasApplied" BOOLEAN NOT NULL DEFAULT false,
    "wasAccepted" BOOLEAN NOT NULL DEFAULT false,
    "wasRejected" BOOLEAN NOT NULL DEFAULT false,
    "generatedAt" TEXT,
    "decidedAt" TEXT,
    "decidedBy" TEXT
);

-- CreateTable
CREATE TABLE "ai_transition_snapshots" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "wellId" TEXT,
    "configId" TEXT,
    "transitionNo" INTEGER,
    "dn" TEXT,
    "transitionType" TEXT,
    "producer" TEXT,
    "heightFromBottomMm" REAL,
    "angleDeg" REAL,
    "position" TEXT,
    "collided" BOOLEAN NOT NULL DEFAULT false,
    "affectedDennicaHeight" REAL,
    "affectedRingSelection" BOOLEAN NOT NULL DEFAULT false,
    "affectedReductionChoice" BOOLEAN NOT NULL DEFAULT false,
    "affectedFinalConfig" BOOLEAN NOT NULL DEFAULT false,
    "minimalDennicaForTransitionsMm" REAL,
    "solverModifiedForTransitions" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TEXT
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "oldData" TEXT,
    "newData" TEXT,
    "createdAt" TEXT
);

-- CreateTable
CREATE TABLE "clients_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "name" TEXT,
    "nip" TEXT,
    "address" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "contact" TEXT DEFAULT '',
    "clientNumber" TEXT DEFAULT '',
    "createdAt" TEXT,
    "updatedAt" TEXT
);

-- CreateTable
CREATE TABLE "offer_items_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "offerId" TEXT,
    "productId" TEXT,
    "quantity" REAL,
    "discount" REAL,
    "price" REAL
);

-- CreateTable
CREATE TABLE "offer_studnie_items_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "offerId" TEXT,
    "productId" TEXT,
    "quantity" REAL,
    "discount" REAL,
    "price" REAL,
    "dodatkowe_info" TEXT
);

-- CreateTable
CREATE TABLE "offers_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "clientId" TEXT,
    "state" TEXT,
    "createdAt" TEXT,
    "transportCost" REAL,
    "offer_number" TEXT,
    "data" TEXT,
    "updatedAt" TEXT,
    "history" TEXT DEFAULT '[]',
    "clientName" TEXT,
    "investName" TEXT,
    "clientNip" TEXT,
    "clientNumber" TEXT DEFAULT ''
);

-- CreateTable
CREATE TABLE "offers_studnie_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "clientId" TEXT,
    "state" TEXT,
    "createdAt" TEXT,
    "transportCost" REAL,
    "offer_number" TEXT,
    "data" TEXT,
    "updatedAt" TEXT,
    "history" TEXT DEFAULT '[]',
    "clientName" TEXT,
    "investName" TEXT,
    "clientNip" TEXT,
    "clientNumber" TEXT DEFAULT ''
);

-- CreateTable
CREATE TABLE "order_counters" (
    "userId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "lastNumber" INTEGER DEFAULT 0,

    PRIMARY KEY ("userId", "year")
);

-- CreateTable
CREATE TABLE "order_counters_rury" (
    "userId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "lastNumber" INTEGER DEFAULT 0,

    PRIMARY KEY ("userId", "year")
);

-- CreateTable
CREATE TABLE "orders_studnie_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "offerStudnieId" TEXT,
    "createdAt" TEXT,
    "status" TEXT,
    "data" TEXT
);

-- CreateTable
CREATE TABLE "orders_rury_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "offerId" TEXT,
    "createdAt" TEXT,
    "status" TEXT,
    "data" TEXT
);

-- CreateTable
CREATE TABLE "production_order_counters" (
    "userId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "lastNumber" INTEGER DEFAULT 0,

    PRIMARY KEY ("userId", "year")
);

-- CreateTable
CREATE TABLE "production_orders_rel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "orderId" TEXT,
    "wellId" TEXT,
    "elementIndex" INTEGER,
    "elementKey" TEXT,
    "createdAt" TEXT,
    "updatedAt" TEXT,
    "data" TEXT,
    "creatorId" TEXT DEFAULT ''
);

-- CreateTable
CREATE TABLE "recycled_production_numbers" (
    "userId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "seqNumber" INTEGER NOT NULL,

    PRIMARY KEY ("userId", "year", "seqNumber")
);

-- CreateTable
CREATE TABLE "sessions" (
    "token" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "createdAt" BIGINT NOT NULL
);

-- CreateTable
CREATE TABLE "settings" (
    "key" TEXT NOT NULL PRIMARY KEY,
    "value" TEXT
);

-- CreateTable
CREATE TABLE "ProductsRury" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "price" REAL NOT NULL,
    "transport" REAL,
    "weight" REAL,
    "area" REAL
);

-- CreateTable
CREATE TABLE "ProductsRuryDefault" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "price" REAL NOT NULL,
    "transport" REAL,
    "weight" REAL,
    "area" REAL
);

-- CreateTable
CREATE TABLE "ProductsStudnie" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "componentType" TEXT NOT NULL,
    "dn" TEXT,
    "height" INTEGER,
    "weight" REAL,
    "price" REAL NOT NULL DEFAULT 0,
    "area" REAL,
    "areaExt" REAL,
    "transport" REAL,
    "magazynWL" BOOLEAN NOT NULL DEFAULT false,
    "magazynKLB" BOOLEAN NOT NULL DEFAULT false,
    "formaStandardowa" BOOLEAN NOT NULL DEFAULT false,
    "formaStandardowaKLB" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT false,
    "zapasDol" INTEGER,
    "zapasGora" INTEGER,
    "zapasDolMin" INTEGER,
    "zapasGoraMin" INTEGER,
    "spocznikH" TEXT,
    "hMin1" INTEGER,
    "hMax1" INTEGER,
    "cena1" REAL,
    "hMin2" INTEGER,
    "hMax2" INTEGER,
    "cena2" REAL,
    "hMin3" INTEGER,
    "hMax3" INTEGER,
    "cena3" REAL,
    "doplataPEHD" REAL,
    "doplataZelbet" REAL,
    "doplataDrabNierdzewna" REAL,
    "malowanieWewnetrzne" REAL,
    "malowanieZewnetrzne" REAL
);

-- CreateTable
CREATE TABLE "ProductsStudnieDefault" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "componentType" TEXT NOT NULL,
    "dn" TEXT,
    "height" INTEGER,
    "weight" REAL,
    "price" REAL NOT NULL DEFAULT 0,
    "area" REAL,
    "areaExt" REAL,
    "transport" REAL,
    "magazynWL" BOOLEAN NOT NULL DEFAULT false,
    "magazynKLB" BOOLEAN NOT NULL DEFAULT false,
    "formaStandardowa" BOOLEAN NOT NULL DEFAULT false,
    "formaStandardowaKLB" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT false,
    "zapasDol" INTEGER,
    "zapasGora" INTEGER,
    "zapasDolMin" INTEGER,
    "zapasGoraMin" INTEGER,
    "spocznikH" TEXT,
    "hMin1" INTEGER,
    "hMax1" INTEGER,
    "cena1" REAL,
    "hMin2" INTEGER,
    "hMax2" INTEGER,
    "cena2" REAL,
    "hMin3" INTEGER,
    "hMax3" INTEGER,
    "cena3" REAL,
    "doplataPEHD" REAL,
    "doplataZelbet" REAL,
    "doplataDrabNierdzewna" REAL,
    "malowanieWewnetrzne" REAL,
    "malowanieZewnetrzne" REAL
);

-- CreateTable
CREATE TABLE "PrecoKonfig" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "PrecoKinety" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "order" INTEGER NOT NULL,
    "dn" INTEGER NOT NULL,
    "wellDn" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "cena" REAL NOT NULL
);

-- CreateTable
CREATE TABLE "PrecoZakresy" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "order" INTEGER NOT NULL,
    "label" TEXT NOT NULL,
    "min" INTEGER NOT NULL,
    "max" INTEGER NOT NULL,
    "grupy" TEXT NOT NULL,
    "wellDn" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "PrecoKonfigDefault" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "PrecoKinetyDefault" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "order" INTEGER NOT NULL,
    "dn" INTEGER NOT NULL,
    "wellDn" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "cena" REAL NOT NULL
);

-- CreateTable
CREATE TABLE "PrecoZakresyDefault" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "order" INTEGER NOT NULL,
    "label" TEXT NOT NULL,
    "min" INTEGER NOT NULL,
    "max" INTEGER NOT NULL,
    "grupy" TEXT NOT NULL,
    "wellDn" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "AiFeature" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "telemetryId" TEXT,
    "dn" INTEGER NOT NULL,
    "heightMm" INTEGER NOT NULL,
    "warehouse" TEXT NOT NULL,
    "wellType" TEXT NOT NULL,
    "hasReduction" BOOLEAN NOT NULL DEFAULT false,
    "hasPsiaBuda" BOOLEAN NOT NULL DEFAULT false,
    "hasStyczna" BOOLEAN NOT NULL DEFAULT false,
    "ringCount" INTEGER NOT NULL DEFAULT 0,
    "bottomType" TEXT NOT NULL,
    "topType" TEXT NOT NULL,
    "kinetaType" TEXT,
    "dennicaHeight" REAL,
    "connectionCount" INTEGER NOT NULL DEFAULT 0,
    "transitionsAboveDennica" INTEGER NOT NULL DEFAULT 0,
    "totalPrice" REAL NOT NULL DEFAULT 0,
    "totalWeight" REAL NOT NULL DEFAULT 0,
    "ringVariety" REAL NOT NULL DEFAULT 0,
    "season" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "reward" REAL NOT NULL DEFAULT 0,
    "decisionMs" INTEGER,
    "createdAt" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "AiModel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "version" TEXT NOT NULL,
    "weights" TEXT NOT NULL,
    "bias" REAL NOT NULL,
    "metrics" TEXT NOT NULL,
    "features" TEXT NOT NULL,
    "featureMins" TEXT NOT NULL,
    "featureMaxs" TEXT NOT NULL,
    "trainingRows" INTEGER NOT NULL,
    "featureVersion" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "createdAt" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "AiEvaluation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "modelVersion" TEXT NOT NULL,
    "acceptance" REAL NOT NULL DEFAULT 0,
    "decisionMsAvg" REAL NOT NULL DEFAULT 0,
    "rewardsAvg" REAL NOT NULL DEFAULT 0,
    "totalDecisions" INTEGER NOT NULL DEFAULT 0,
    "triggeredAt" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "aiRewardLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "wellId" TEXT NOT NULL,
    "dn" INTEGER NOT NULL,
    "action" TEXT NOT NULL,
    "reward" REAL NOT NULL,
    "scoreBefore" REAL,
    "scoreAfter" REAL,
    "wasAiRanked" BOOLEAN NOT NULL DEFAULT false,
    "configSnapshot" TEXT,
    "createdAt" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "firstName" TEXT,
    "lastName" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "symbol" TEXT,
    "subUsers" TEXT,
    "createdAt" TEXT,
    "orderStartNumber" INTEGER DEFAULT 1,
    "productionOrderStartNumber" INTEGER DEFAULT 1,
    "totalReward" REAL DEFAULT 0
);

-- CreateIndex
CREATE INDEX "idx_logs_wasmodified" ON "ai_telemetry_logs"("wasModified");

-- CreateIndex
CREATE INDEX "idx_logs_createdat" ON "ai_telemetry_logs"("createdAt");

-- CreateIndex
CREATE INDEX "idx_logs_dn" ON "ai_telemetry_logs"("dn");

-- CreateIndex
CREATE INDEX "idx_logs_well" ON "ai_telemetry_logs"("wellId");

-- CreateIndex
CREATE INDEX "idx_logs_source_well" ON "ai_telemetry_logs"("solverSource", "wellId");

-- CreateIndex
CREATE INDEX "idx_logs_modified_created" ON "ai_telemetry_logs"("wasModified", "createdAt");

-- CreateIndex
CREATE INDEX "idx_events_telemetry" ON "ai_telemetry_events"("telemetryId");

-- CreateIndex
CREATE INDEX "idx_events_well" ON "ai_telemetry_events"("wellId");

-- CreateIndex
CREATE INDEX "idx_events_type" ON "ai_telemetry_events"("eventType");

-- CreateIndex
CREATE INDEX "idx_events_user" ON "ai_telemetry_events"("userId");

-- CreateIndex
CREATE INDEX "idx_events_createdat" ON "ai_telemetry_events"("createdAt");

-- CreateIndex
CREATE INDEX "idx_history_well" ON "ai_config_history"("wellId");

-- CreateIndex
CREATE INDEX "idx_history_well_current" ON "ai_config_history"("wellId", "isCurrent");

-- CreateIndex
CREATE INDEX "idx_versions_active" ON "ai_telemetry_versions"("componentType", "isActive");

-- CreateIndex
CREATE INDEX "idx_kb_pattern_type" ON "ai_knowledge_base"("patternType");

-- CreateIndex
CREATE INDEX "idx_kb_dn" ON "ai_knowledge_base"("dn");

-- CreateIndex
CREATE INDEX "idx_kb_pattern_key" ON "ai_knowledge_base"("patternKey");

-- CreateIndex
CREATE INDEX "idx_kb_status" ON "ai_knowledge_base"("status");

-- CreateIndex
CREATE INDEX "idx_kb_confidence" ON "ai_knowledge_base"("confidence");

-- CreateIndex
CREATE INDEX "idx_recs_type" ON "ai_recommendations"("patternType");

-- CreateIndex
CREATE INDEX "idx_recs_well" ON "ai_recommendations"("wellId");

-- CreateIndex
CREATE INDEX "idx_recs_applied" ON "ai_recommendations"("wasApplied");

-- CreateIndex
CREATE INDEX "idx_transitions_well" ON "ai_transition_snapshots"("wellId");

-- CreateIndex
CREATE INDEX "idx_transitions_config" ON "ai_transition_snapshots"("configId");

-- CreateIndex
CREATE INDEX "idx_audit_entity" ON "audit_logs"("entityType", "entityId");

-- CreateIndex
CREATE INDEX "idx_audit_created_at" ON "audit_logs"("createdAt");

-- CreateIndex
CREATE INDEX "idx_clients_user" ON "clients_rel"("userId");

-- CreateIndex
CREATE INDEX "idx_offitems_offer" ON "offer_items_rel"("offerId");

-- CreateIndex
CREATE INDEX "idx_offstitems_offer" ON "offer_studnie_items_rel"("offerId");

-- CreateIndex
CREATE INDEX "idx_offers_user" ON "offers_rel"("userId");

-- CreateIndex
CREATE INDEX "idx_offers_created" ON "offers_rel"("createdAt");

-- CreateIndex
CREATE INDEX "idx_offers_state" ON "offers_rel"("state");

-- CreateIndex
CREATE INDEX "idx_offers_number" ON "offers_rel"("offer_number");

-- CreateIndex
CREATE INDEX "idx_offers_clientname" ON "offers_rel"("clientName");

-- CreateIndex
CREATE INDEX "idx_offers_investname" ON "offers_rel"("investName");

-- CreateIndex
CREATE INDEX "idx_offersstud_user" ON "offers_studnie_rel"("userId");

-- CreateIndex
CREATE INDEX "idx_offersstud_created" ON "offers_studnie_rel"("createdAt");

-- CreateIndex
CREATE INDEX "idx_offersstud_state" ON "offers_studnie_rel"("state");

-- CreateIndex
CREATE INDEX "idx_offersstud_number" ON "offers_studnie_rel"("offer_number");

-- CreateIndex
CREATE INDEX "idx_offersstud_clientname" ON "offers_studnie_rel"("clientName");

-- CreateIndex
CREATE INDEX "idx_offersstud_investname" ON "offers_studnie_rel"("investName");

-- CreateIndex
CREATE INDEX "idx_ordstud_user" ON "orders_studnie_rel"("userId");

-- CreateIndex
CREATE INDEX "idx_ordstud_offer" ON "orders_studnie_rel"("offerStudnieId");

-- CreateIndex
CREATE INDEX "idx_ordrury_user" ON "orders_rury_rel"("userId");

-- CreateIndex
CREATE INDEX "idx_ordrury_offer" ON "orders_rury_rel"("offerId");

-- CreateIndex
CREATE INDEX "idx_prod_user" ON "production_orders_rel"("userId");

-- CreateIndex
CREATE INDEX "idx_prod_creator" ON "production_orders_rel"("creatorId");

-- CreateIndex
CREATE INDEX "idx_prod_created" ON "production_orders_rel"("createdAt");

-- CreateIndex
CREATE INDEX "idx_prod_order" ON "production_orders_rel"("orderId");

-- CreateIndex
CREATE INDEX "idx_aifeatures_key" ON "AiFeature"("dn", "warehouse", "wellType");

-- CreateIndex
CREATE INDEX "idx_aifeatures_label" ON "AiFeature"("label");

-- CreateIndex
CREATE INDEX "idx_aifeatures_created" ON "AiFeature"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "AiModel_version_key" ON "AiModel"("version");

-- CreateIndex
CREATE INDEX "idx_aimodel_active" ON "AiModel"("active");

-- CreateIndex
CREATE INDEX "idx_aimodel_created" ON "AiModel"("createdAt");

-- CreateIndex
CREATE INDEX "idx_aieval_model" ON "AiEvaluation"("modelVersion");

-- CreateIndex
CREATE INDEX "idx_aieval_triggered" ON "AiEvaluation"("triggeredAt");

-- CreateIndex
CREATE INDEX "idx_reward_user" ON "aiRewardLog"("userId");

-- CreateIndex
CREATE INDEX "idx_reward_action" ON "aiRewardLog"("action");

-- CreateIndex
CREATE INDEX "idx_reward_created" ON "aiRewardLog"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE INDEX "idx_users_role" ON "users"("role");

